### ISSUE TITLE
webtorrent package with browserify-versionify transform fails

### ISSUE THREAD

**Issue by feross** [jesusabdullah/browserify-cdn#92]
http://wzrd.in/standalone/webtorrent@latest gives me:

```
---FLAGRANT SYSTEM ERROR---

(logs uuid: 38b6fb60-90d4-11e4-94c6-21fd5733c6b1 )

Error: "browserify exited with code 8"

code: 8
stderr: 
/tmp/webtorrent1141131-17698-1vv21i9/node_modules/webtorrent/node_modules/browserify-versionify/node_modules/find-root/index.js:13
    throw new Error('package.json not found in path')
          ^
Error: package.json not found in path
    at findRoot (/tmp/webtorrent1141131-17698-1vv21i9/node_modules/webtorrent/node_modules/browserify-versionify/node_modules/find-root/index.js:13:11)
    at findRoot (/tmp/webtorrent1141131-17698-1vv21i9/node_modules/webtorrent/node_modules/browserify-versionify/node_modules/find-root/index.js:20:10)
    at findRoot (/tmp/webtorrent1141131-17698-1vv21i9/node_modules/webtorrent/node_modules/browserify-versionify/node_modules/find-root/index.js:20:10)
    at findRoot (/tmp/webtorrent1141131-17698-1vv21i9/node_modules/webtorrent/node_modules/browserify-versionify/node_modules/find-root/index.js:20:10)
    at findRoot (/tmp/webtorrent1141131-17698-1vv21i9/node_modules/webtorrent/node_modules/browserify-versionify/node_modules/find-root/index.js:20:10)
    at versionify (/tmp/webtorrent1141131-17698-1vv21i9/node_modules/webtorrent/node_modules/browserify-versionify/index.js:12:31)
    at Object.<anonymous> (/tmp/webtorrent1141131-17698-1vv21i9/node_modules/webtorrent/node_modules/browserify-versionify/index.js:23:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

dirPath: /tmp/webtorrent1141131-17698-1vv21i9

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jesusabdullah/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and he can
try to help you out.

Have a nice day!
```

**Comment by feross** [comment]
Yes, `webtorrent` definitely browserifies by normal means.

**Comment by feross** [comment]
Thanks!
